name:                project-euler
version:             0.1.0.0
github:              "githubuser/project-euler"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/project-euler#readme>

dependencies:
- base >= 4.7 && < 5
- arithmoi
- array
- containers
- directory
- filepath
- hspec
- matrix
- monad-memo
- mtl
- optparse-applicative
- random
- time
- transformers
- QuickCheck
- wide-word
- word8

library:
  source-dirs: src

executables:
  euler:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    dependencies:
    - project-euler

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -O2
    dependencies:
    - project-euler