[package]
name = "project_euler"
version = "0.1.0"
authors = ["Alek"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
primal = "0.2.3"