[package]
name = "project-euler-rust-macros"
version = "0.1.0"
authors = ["a-wiacek <33523701+a-wiacek@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true